version: 2
updates:
  - package-ecosystem: 'npm'
    reviewers:
      - 'Parsely/wp-parsely'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
