name: CI (Grunt)

on:
  push:
  workflow_dispatch:

concurrency:
  group: ci-grunt-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "18"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: Run Grunt tasks
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3.3.0

      - name: Set up Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          caching: true

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run postinstall scripts
        run: npm rebuild && npm run prepare --if-present

      - name: Run build tasks
        run: npm run build
