<?php

use function Automattic\VIP\Schema\_parse_indices;

require_once ABSPATH . '/wp-admin/includes/upgrade.php';

class VIP_Go_Schema_Test extends WP_UnitTestCase {
	public function test__dbDelta__verify_blog_tables() {
		$deltas = dbDelta( 'blog', false ); // phpcs:ignore WordPressVIPMinimum.Functions.RestrictedFunctions.dbDelta_dbdelta
		
		$this->assertCount( 1, $deltas, 'More deltas than expected for blogs table' );
		$this->assertEquals( $deltas[0], 'Added index wptests_postmeta KEY `vip_meta_key_value` (`meta_key`(191),`meta_value`(100))', 'Delta did not find vip_meta_key_value index or assertion needs updating.' );
	}

	public function test__get_table_indices(): void {
		$indices = [
			[
				'Table'         => 'test',
				'Non_unique'    => '0',
				'Key_name'      => 'PRIMARY',
				'Seq_in_index'  => '1',
				'Column_name'   => 'id',
				'Collation'     => 'A',
				'Cardinality'   => '242386',
				'Sub_part'      => null,
				'Packed'        => null,
				'Null'          => '',
				'Index_type'    => 'BTREE',
				'Comment'       => '',
				'Index_comment' => '',
			],
			[
				'Table'         => 'test',
				'Non_unique'    => '1',
				'Key_name'      => 'active',
				'Seq_in_index'  => '1',
				'Column_name'   => 'active',
				'Collation'     => 'A',
				'Cardinality'   => '4',
				'Sub_part'      => null,
				'Packed'        => null,
				'Null'          => '',
				'Index_type'    => 'BTREE',
				'Comment'       => '',
				'Index_comment' => '',
			],
			[
				'Table'         => 'test',
				'Non_unique'    => '1',
				'Key_name'      => 'active',
				'Seq_in_index'  => '2',
				'Column_name'   => 'last_modified',
				'Collation'     => 'A',
				'Cardinality'   => '121193',
				'Sub_part'      => null,
				'Packed'        => null,
				'Null'          => '',
				'Index_type'    => 'BTREE',
				'Comment'       => '',
				'Index_comment' => '',
			],
			[
				'Table'         => 'test',
				'Non_unique'    => '1',
				'Key_name'      => 'last_modified',
				'Seq_in_index'  => '1',
				'Column_name'   => 'last_modified',
				'Collation'     => 'A',
				'Cardinality'   => '80795',
				'Sub_part'      => null,
				'Packed'        => null,
				'Null'          => '',
				'Index_type'    => 'BTREE',
				'Comment'       => '',
				'Index_comment' => '',
			],
			[
				'Table'         => 'test',
				'Non_unique'    => '1',
				'Key_name'      => 'name',
				'Seq_in_index'  => '1',
				'Column_name'   => 'name',
				'Collation'     => 'A',
				'Cardinality'   => '242386',
				'Sub_part'      => null,
				'Packed'        => null,
				'Null'          => '',
				'Index_type'    => 'BTREE',
				'Comment'       => '',
				'Index_comment' => '',
			],
			[
				'Table'         => 'test',
				'Non_unique'    => '1',
				'Key_name'      => 'name',
				'Seq_in_index'  => '2',
				'Column_name'   => 'active',
				'Collation'     => 'A',
				'Cardinality'   => '242386',
				'Sub_part'      => null,
				'Packed'        => null,
				'Null'          => '',
				'Index_type'    => 'BTREE',
				'Comment'       => '',
				'Index_comment' => '',
			],
			[
				'Table'         => 'test',
				'Non_unique'    => '1',
				'Key_name'      => 'address',
				'Seq_in_index'  => '1',
				'Column_name'   => 'address',
				'Collation'     => 'A',
				'Cardinality'   => '242386',
				'Sub_part'      => '255',
				'Packed'        => null,
				'Null'          => '',
				'Index_type'    => 'BTREE',
				'Comment'       => '',
				'Index_comment' => '',
			],
			[
				'Table'         => 'test',
				'Non_unique'    => '1',
				'Key_name'      => 'address',
				'Seq_in_index'  => '2',
				'Column_name'   => 'active',
				'Collation'     => 'A',
				'Cardinality'   => '242386',
				'Sub_part'      => null,
				'Packed'        => null,
				'Null'          => '',
				'Index_type'    => 'BTREE',
				'Comment'       => '',
				'Index_comment' => '',
			],
			[
				'Table'         => 'test',
				'Non_unique'    => '1',
				'Key_name'      => 'country',
				'Seq_in_index'  => '1',
				'Column_name'   => 'country',
				'Collation'     => 'A',
				'Cardinality'   => '682',
				'Sub_part'      => null,
				'Packed'        => null,
				'Null'          => '',
				'Index_type'    => 'BTREE',
				'Comment'       => '',
				'Index_comment' => '',
			],
			[
				'Table'         => 'test',
				'Non_unique'    => '1',
				'Key_name'      => 'country',
				'Seq_in_index'  => '2',
				'Column_name'   => 'active',
				'Collation'     => 'A',
				'Cardinality'   => '708',
				'Sub_part'      => null,
				'Packed'        => null,
				'Null'          => '',
				'Index_type'    => 'BTREE',
				'Comment'       => '',
				'Index_comment' => '',
			],
			[
				'Table'         => 'test',
				'Non_unique'    => '1',
				'Key_name'      => 'status',
				'Seq_in_index'  => '1',
				'Column_name'   => 'status',
				'Collation'     => 'A',
				'Cardinality'   => '12',
				'Sub_part'      => null,
				'Packed'        => null,
				'Null'          => '',
				'Index_type'    => 'BTREE',
				'Comment'       => '',
				'Index_comment' => '',
			],
			[
				'Table'         => 'test',
				'Non_unique'    => '1',
				'Key_name'      => 'slug',
				'Seq_in_index'  => '1',
				'Column_name'   => 'slug',
				'Collation'     => 'A',
				'Cardinality'   => '242386',
				'Sub_part'      => null,
				'Packed'        => null,
				'Null'          => '',
				'Index_type'    => 'BTREE',
				'Comment'       => '',
				'Index_comment' => '',
			],
			[
				'Table'         => 'test',
				'Non_unique'    => '1',
				'Key_name'      => 'slug',
				'Seq_in_index'  => '2',
				'Column_name'   => 'status',
				'Collation'     => 'A',
				'Cardinality'   => '242386',
				'Sub_part'      => null,
				'Packed'        => null,
				'Null'          => '',
				'Index_type'    => 'BTREE',
				'Comment'       => '',
				'Index_comment' => '',
			],
			[
				'Table'         => 'test',
				'Non_unique'    => '1',
				'Key_name'      => 'description',
				'Seq_in_index'  => '1',
				'Column_name'   => 'description',
				'Collation'     => null,
				'Cardinality'   => null,
				'Sub_part'      => null,
				'Packed'        => null,
				'Null'          => '',
				'Index_type'    => 'FULLTEXT',
				'Comment'       => '',
				'Index_comment' => '',
			],
		];

		$expected = [
			'PRIMARY'       => 'PRIMARY KEY  (`id`)',
			'active'        => 'KEY `active` (`active`, `last_modified`)',
			'last_modified' => 'KEY `last_modified` (`last_modified`)',
			'name'          => 'KEY `name` (`name`, `active`)',
			'address'       => 'KEY `address` (`address`(255), `active`)',
			'country'       => 'KEY `country` (`country`, `active`)',
			'status'        => 'KEY `status` (`status`)',
			'slug'          => 'KEY `slug` (`slug`, `status`)',
			'description'   => 'FULLTEXT KEY `description` (`description`)',
		];

		$actual = _parse_indices( $indices );
		
		self::assertEquals( $expected, $actual );
	}
}
