workflows:
  version: 2
  main:
    jobs:
      - php73-build-multisite
      - php73-build-singlesite

version: 2

job-references:
  db_image: &db_image
    circleci/mariadb:10.2

  setup_environment: &setup_environment
    name: "Setup Environment Variables"
    command: |
      echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $BASH_ENV
      source /home/circleci/.bashrc

  install_dependencies: &install_dependencies
    name: "Install Dependencies"
    command: |
      sudo apt-get update && sudo apt-get install subversion libgcc-10-dev default-mysql-client
      sudo -E docker-php-ext-install mysqli 
      composer install -n

  prepare_repo: &prepare_repo
    name: "Prepare Repo"
    command: |
      git submodule update --init --recursive

  php_job: &php_job
    environment:
      - WP_TESTS_DIR: "/tmp/wordpress-tests-lib"
      - WP_CORE_DIR: "/tmp/wordpress/"
    steps:
      - checkout
      - run: *setup_environment
      - run: *install_dependencies
      - run: *prepare_repo
      - run:
          name: "Run Tests"
          command: |
            make lint
            rm -rf $WP_TESTS_DIR $WP_CORE_DIR
            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION
            vendor/bin/phpunit --version
            vendor/bin/phpunit

jobs:
  php73-build-multisite:
    <<: *php_job
    environment:
      - WP_MULTISITE: "1"
      - WP_VERSION: "latest"
    docker:
      - image: circleci/php:7.3
      - image: *db_image

  php73-build-singlesite:
    <<: *php_job
    environment:
      - WP_MULTISITE: "0"
      - WP_VERSION: "latest"
    docker:
      - image: circleci/php:7.3
      - image: *db_image

