#!/bin/bash

COMMAND="$1 $2 $3 $4"

case "$COMMAND" in
	"cron-control orchestrate sites list")
		echo '[{"url":"https:\/\/example-com.go-vip.net"},{"url":"https:\/\/example-com.go-vip.net/subsite1"}]'
		;;

	"cron-control orchestrate runner-only get-info")
		echo '[{"multisite":1,"siteurl":"https:\/\/example-com.go-vip.net","disabled":0}]'
		;;

	"cron-control orchestrate runner-only list-due-batch")
		echo '[{"timestamp":1586382738,"action":"b05eecbc20fcb6b338510de2e15ca4fa","instance":"40cd750bba9870f18aada2478b24840a"},{"timestamp":1586382759,"action":"033bc12724f6f8285fd89ab813c47e4b","instance":"40cd750bba9870f18aada2478b24840a"},{"timestamp":1586382766,"action":"85ede02876b7c1557e7e623428f6cfc7","instance":"40cd750bba9870f18aada2478b24840a"},{"timestamp":1586382566,"action":"7715f1b533e885efdb5e3ef10d2ba3e8","instance":"40cd750bba9870f18aada2478b24840a"},{"timestamp":1586382591,"action":"29ef625a054a0b386093ac9c46a2c616","instance":"40cd750bba9870f18aada2478b24840a"}]'
		;;

	"cron-control orchestrate runner-only run")
		sleep 200
		echo "$@"
		echo "Success"
		;;
esac
