<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'jetpack',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-admin-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-admin-ui',
      'ver' => '0.2.10',
    ),
    'jetpack-connection' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection',
      'ver' => '1.41.4',
    ),
    'jetpack-password-checker' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-password-checker',
      'ver' => '0.2.5',
    ),
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '1.17.19',
    ),
    'jetpack-idc' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-identity-crisis',
      'ver' => '0.8.15',
    ),
    'jetpack-sync' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-sync',
      'ver' => '1.36.1',
    ),
    'jetpack-plugins-installer' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-plugins-installer',
      'ver' => '0.1.3',
    ),
    'jetpack-licensing' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-licensing',
      'ver' => '1.7.4',
    ),
    'jetpack-connection-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection-ui',
      'ver' => '2.4.9',
    ),
    'jetpack-config' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-config',
      'ver' => '1.9.2',
    ),
    'jetpack-my-jetpack' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-my-jetpack',
      'ver' => '1.7.2',
    ),
    'jetpack-compat' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-compat',
      'ver' => '1.7.3',
    ),
    'jetpack-lazy-images' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-lazy-images',
      'ver' => '2.1.20',
    ),
    'jetpack-backup-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-backup',
      'ver' => '1.4.3',
    ),
    'jetpack-google-fonts-provider' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-google-fonts-provider',
      'ver' => '0.3.3',
    ),
    'jetpack-jitm' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-jitm',
      'ver' => '2.2.21',
    ),
    'jetpack-publicize-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-publicize',
      'ver' => '0.7.1',
    ),
    'jetpack-search-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-search',
      'ver' => '0.15.3',
    ),
    'jetpack-waf' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-waf',
      'ver' => '0.6.4',
    ),
    'jetpack-wordads' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-wordads',
      'ver' => '0.2.7',
    ),
  ),
);
