<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'jetpack',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-admin-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-admin-ui',
      'ver' => '0.2.11',
    ),
    'jetpack-connection' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection',
      'ver' => '1.44.0',
    ),
    'jetpack-password-checker' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-password-checker',
      'ver' => '0.2.6',
    ),
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '1.17.21',
    ),
    'jetpack-idc' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-identity-crisis',
      'ver' => '0.8.22',
    ),
    'jetpack-sync' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-sync',
      'ver' => '1.38.2',
    ),
    'jetpack-plugins-installer' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-plugins-installer',
      'ver' => '0.2.0',
    ),
    'jetpack-licensing' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-licensing',
      'ver' => '1.7.8',
    ),
    'jetpack-jitm' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-jitm',
      'ver' => '2.2.26',
    ),
    'jetpack-my-jetpack' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-my-jetpack',
      'ver' => '2.0.3',
    ),
    'jetpack-connection-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection-ui',
      'ver' => '2.4.15',
    ),
    'jetpack-config' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-config',
      'ver' => '1.9.6',
    ),
    'jetpack-backup-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-backup',
      'ver' => '1.7.3',
    ),
    'jetpack-compat' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-compat',
      'ver' => '1.7.4',
    ),
    'jetpack-google-fonts-provider' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-google-fonts-provider',
      'ver' => '0.3.4',
    ),
    'jetpack-lazy-images' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-lazy-images',
      'ver' => '2.1.22',
    ),
    'jetpack-post-list' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-post-list',
      'ver' => '0.4.0',
    ),
    'jetpack-publicize-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-publicize',
      'ver' => '0.12.1',
    ),
    'jetpack-search-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-search',
      'ver' => '0.21.1',
    ),
    'jetpack-waf' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-waf',
      'ver' => '0.6.5',
    ),
    'jetpack-videopress-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-videopress',
      'ver' => '0.2.1',
    ),
    'jetpack-wordads' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-wordads',
      'ver' => '0.2.13',
    ),
  ),
);
