export const RECOMMENDATIONS_BLOCK_ERROR = 'RECOMMENDATIONS_BLOCK_ERROR';
export const RECOMMENDATIONS_BLOCK_LOADED = 'RECOMMENDATIONS_BLOCK_LOADED';
export const RECOMMENDATIONS_BLOCK_RECOMMENDATIONS = 'RECOMMENDATIONS_BLOCK_RECOMMENDATIONS';
