sudo: false

language: php

php:
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.4 WP_MULTISITE=0
    - WP_VERSION=4.4 WP_MULTISITE=1

matrix:
    include:
        - php: 7.0
          env: WP_VERSION=latest WP_MULTISITE=0
    allow_failures:
        - php: 7.0
    fast_finish: true

services:
    - elasticsearch

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - sleep 5 # ensure ES is running

script: phpunit
