# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    paths:
      - .github/workflows/*.js.yml
      - '**/*[tj]sx?'
      - package*.json
  push:
    paths:
      - .github/workflows/*.js.yml
      - '**/*[tj]sx?'
      - package*.json
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install JavaScript dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Confirm the build is up-to-date
        run: |
          REPOSTATUS=`git status --porcelain 2>/dev/null`;
          if [[ -n "$REPOSTATUS" ]]; then
            echo "Repo is not clean. Did you forget to commit changes to the /build dir?";
            echo "$REPOSTATUS";
            exit 1;
          else
            echo "The repo file system is clean (build files are present and up to date).";
          fi

      - name: Run tests
        run: npm test
