<?php

use function Automattic\Test\Utils\get_class_method_as_public;
use function Automattic\Test\Utils\get_class_property_as_public;

require_once __DIR__ . '/../../files/class-image.php';

/**
 * Class A8C_Files_Image_Test
 *
 * @group srcset
 */
class A8C_Files_Image_Test extends WP_UnitTestCase {

	/**
	 * The test image.
	 *
	 * @var string
	 */
	const TEST_IMAGE = VIP_GO_MUPLUGINS_TESTS__DIR__ . '/fixtures/image.jpg'; //@todo: consider using `DIR_TESTDATA . '/images/canola.jpg';`

	/**
	 * The test image's attachment metadata, as generated by WordPress.
	 *
	 * Shared by all tests: the Image class only reads it, so it is generated once.
	 *
	 * @var array
	 */
	private static $postmeta;

	public static function wpSetUpBeforeClass( WP_UnitTest_Factory $factory ) {
		// Only the original image's metadata is needed; don't create intermediate sizes (VIP never does).
		add_filter( 'intermediate_image_sizes_advanced', '__return_empty_array' );

		$attachment_id = $factory->attachment->create_object( self::TEST_IMAGE, 0, [
			'post_mime_type' => 'image/jpeg',
			'post_type'      => 'attachment',
		] );
		wp_update_attachment_metadata( $attachment_id, wp_generate_attachment_metadata( $attachment_id, self::TEST_IMAGE ) );

		remove_filter( 'intermediate_image_sizes_advanced', '__return_empty_array' );

		self::$postmeta = get_post_meta( $attachment_id, '_wp_attachment_metadata', true );
	}

	/**
	 * Unit test covering the object initialisation.
	 *
	 * @covers Automattic\VIP\Files\Image::__construct
	 */
	public function test__object_construction() {
		$postmeta = self::$postmeta;

		$image = new Automattic\VIP\Files\Image( $postmeta, 'image/jpeg' );

		$this->assertEquals( $postmeta['width'], $image->get_width(), 'Wrong image width.' );
		$this->assertEquals( $postmeta['height'], $image->get_height(), 'Wrong image height.' );
		$this->assertEquals( 'image/jpeg', $image->get_mime_type(), 'Wrong image mime type.' );
		$this->assertEquals( $postmeta['filesize'], $image->get_filesize(), 'Wrong image filesize.' );
		$this->assertFalse( $image->is_resized(), 'Non-resized image is marked as resized.' );

		// If no filesize is passed in, it defaults to 0.
		unset( $postmeta['filesize'] );
		$image = new Automattic\VIP\Files\Image( $postmeta, 'image/jpeg' );
		$this->assertSame( 0, $image->get_filesize(), 'Filesize did not default to 0' );
	}

	/**
	 * Data provider for testing the Automattic\VIP\Files\Image::reset_to_original.
	 *
	 * @return array Array of Arrays of Arrays in order to provide input and expected output.
	 */
	public function get_data_for_generate_sizes() {
		return [
			'thumbnail'    => [
				[
					'width'  => '150',
					'height' => '150',
					'crop'   => '1',
				],
			],
			'medium'       => [
				[
					'width'  => '300',
					'height' => '300',
					'crop'   => false,
				],
			],
			'medium_large' => [
				[
					'width'  => '768',
					'height' => '0',
					'crop'   => false,
				],
			],
			'large'        => [
				[
					'width'  => '1024',
					'height' => '1024',
					'crop'   => false,
				],
			],
		];
	}

	/**
	 * Test the reset of dimensions to original.
	 *
	 * Image::get_size() is covered by A8C_Files_ImageSizes_Test::test__generate_sizes_meta().
	 *
	 * @covers Automattic\VIP\Files\Image::reset_to_original
	 * @dataProvider get_data_for_generate_sizes
	 *
	 * @param array $size Array of requested size dimensions.
	 */
	public function test__reset_to_original( $size ) {
		$postmeta = self::$postmeta;

		$image = new Automattic\VIP\Files\Image( $postmeta, 'image/jpeg' );
		$image->resize( $size );
		$image->reset_to_original();

		$this->assertFalse( $image->is_resized(), 'Image is not marked as NOT resized.' );
		$this->assertEquals( $postmeta['width'], $image->get_width(), 'Width has not been properly reset.' );
		$this->assertEquals( $postmeta['height'], $image->get_height(), 'Height has not been properly reset.' );
		$this->assertEquals( 'image/jpeg', $image->get_mime_type(), 'Mime-type has not been properly reset' );
		$this->assertEquals( 'image.jpg', $image->get_filename(), 'Image after reset does not point to appropriate file.' );
	}

	/**
	 * Test get_resized_filename
	 *
	 * @covers Automattic\VIP\Files\Image::get_resized_filename
	 */
	public function test__get_resized_filename() {
		$image = new Automattic\VIP\Files\Image( self::$postmeta, 'image/jpeg' );
		get_class_property_as_public( Automattic\VIP\Files\Image::class, 'width' )->setValue( $image, 150 );
		get_class_property_as_public( Automattic\VIP\Files\Image::class, 'height' )->setValue( $image, 150 );
		$get_resized_filename = get_class_method_as_public( Automattic\VIP\Files\Image::class, 'get_resized_filename' );

		$this->assertEquals( self::TEST_IMAGE . '?resize=150,150', $get_resized_filename->invokeArgs( $image, [] ) );
	}
}
