<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'jetpack',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-assets' => '0.0.0',
    'jetpack-tracking' => '0.0.0',
    'jetpack-heartbeat' => '0.0.0',
    'jetpack-password-checker' => '0.0.0',
    'jetpack-idc' => '0.0.0',
    'jetpack-sync' => '0.0.0',
    'jetpack-backup-pkg' => '0.0.0',
    'jetpack-connection' => '0.0.0',
    'jetpack-config' => '0.0.0',
    'jetpack-connection-ui' => '0.0.0',
    'jetpack-jitm' => '0.0.0',
    'jetpack-lazy-images' => '0.0.0',
    'jetpack-licensing' => '0.0.0',
    'jetpack-my-jetpack' => '0.0.0',
    'jetpack-search-pkg' => '0.0.0',
  ),
);
