version: 2
updates:
  - directory: /
    open-pull-requests-limit: 15
    package-ecosystem: composer
    schedule:
      interval: daily

  - directory: /
    open-pull-requests-limit: 15
    package-ecosystem: github-actions
    schedule:
      interval: daily

  - directory: /
    open-pull-requests-limit: 15
    package-ecosystem: npm
    schedule:
      interval: daily
