name: Changelog Summary - Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  execute:
    name: Run Summary Generator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Setup PHP
        uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # 2.35.4

      - name: Install
        uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # 3.1.1

      - name: Execute
        env:
          CHANGELOG_POST_TOKEN: ${{ secrets.CHANGELOG_BEARER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          PROJECT_USERNAME: Automattic
          PROJECT_REPONAME: vip-go-mu-plugins
          BRANCH: ${{ github.ref_name }}
        run: |
          php ./ci/changelog-summary.php \
                --wp-endpoint=https://public-api.wordpress.com/wp/v2/sites/wpvipchangelog.wordpress.com/posts \
                --wp-status=draft \
                --debug

  changelog:
    needs: execute
    name: Docs Site Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: Automattic/vip-actions/changelog@52569737661b6dc7474c86d4b608ffb08c0af27a # trunk
        with:
          endpoint: ${{ vars.DOCS_CHANGELOG_POST_ENDPOINT }}
          endpoint-token: ${{ secrets.DOCS_CHANGELOG_POST_TOKEN }}
          endpoint-auth-type: 'basic'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          status: 'draft'
          category-id: '97'
          tag-id: '96'
          link-to-pr: true

