name: Changelog Summary - Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  execute:
    name: Run Summary Generator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@20529878ed81ef8e78ddf08b480401e6101a850f # 2.35.3

      - name: Install
        uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # 3.1.1

      - name: Execute
        env:
          CHANGELOG_POST_TOKEN: ${{ secrets.CHANGELOG_BEARER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          PROJECT_USERNAME: Automattic
          PROJECT_REPONAME: vip-go-mu-plugins
          BRANCH: ${{ github.ref_name }}
        run: |
          php ./ci/changelog-summary.php \
                --wp-endpoint=https://public-api.wordpress.com/wp/v2/sites/wpvipchangelog.wordpress.com/posts \
                --wp-status=draft \
                --debug

  changelog:
    needs: execute
    name: Docs Site Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: Automattic/vip-actions/changelog@8e0e16376698771d5aded6c6d74f3d1f120b7b5a # trunk
        with:
          endpoint: ${{ vars.DOCS_CHANGELOG_POST_ENDPOINT }}
          endpoint-token: ${{ secrets.DOCS_CHANGELOG_POST_TOKEN }}
          endpoint-auth-type: 'basic'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          status: 'draft'
          category-id: '97'
          tag-id: '96'
          link-to-pr: true

