name: CI (PHP 8)

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PHPUNIT_VERSION: "9"
  PHP_VERSION: "8.0"

jobs:
  test:
    name: "WordPress ${{ matrix.wp }}, multisite: ${{ matrix.multisite }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wp:
          - "latest"
          - "nightly"
        multisite:
          - "yes"
          - "no"
    steps:
      - name: Check out source code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          submodules: recursive

      - name: Set up PHP
        uses: shivammathur/setup-php@3eda58347216592f618bb1dff277810b6698e4ca # tag=2.19.1
        with:
          coverage: none
          php-version: ${{ env.PHP_VERSION }}

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@f680dac46551dffb2234a240d65ae806c2999dd6 # tag=2.1.0

      - name: Run tests
        run: |
          if [ "${{ matrix.multisite }}" = "yes" ]; then
            MULTISITE=1
          else
            MULTISITE=0
          fi
          ./bin/test.sh --wp ${{ matrix.wp }} --multisite ${MULTISITE} --order-by=random
