name: WordPress Nightly

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: "WordPress nightly, multisite: ${{ matrix.multisite }}, PHP ${{ matrix.php }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "7.4"
          - "8.0"
        multisite:
          - "0"
          - "1"
    steps:
      - name: Check out source code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          submodules: recursive

      - name: Set up PHP
        uses: shivammathur/setup-php@3eda58347216592f618bb1dff277810b6698e4ca # tag=2.19.1
        with:
          coverage: none
          php-version: ${{ matrix.php }}

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@f680dac46551dffb2234a240d65ae806c2999dd6 # renovate: tag=2.1.0

      - name: Run tests
        run: ./bin/test.sh --wp nightly --php ${{ matrix.php }} --multisite ${{ matrix.multisite }} --phpunit 9 --order-by=random
