name: Run Tests on PHP 8.x

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: "WordPress ${{ matrix.wp }}, multisite: ${{ matrix.multisite }}, PHP ${{ matrix.php }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.0"
        wp:
          - nightly
        multisite:
          - "0"
          - "1"
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php }}

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@2.1.0

      - name: Run tests
        run: ./bin/test.sh --wp ${{ matrix.wp }} --php ${{ matrix.php }} --multisite ${{ matrix.multisite }} --phpunit 9 --order-by=random
