name: Release - Production

on:
  push:
    branches:
      - production
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tag-release:
    name: Tag Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.id-generator.outputs.id }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Check out source code
        uses: actions/checkout@v6.0.2

      - name: Retrieve tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Get tag name
        id: id-generator
        run: |
          current_date=$(date '+v%Y%m%d.')
          minor_version=0
          tag=$(git tag -l "${current_date}*" --sort=-version:refname | head -n 1)
          if [ -n "${tag}" ]; then
              minor_version=$(echo "${tag}" | awk -F. '{print $2+1}')
          fi

          echo "::set-output name=id::${current_date}${minor_version}"

      - name: Tag release
        run: git tag ${{ steps.id-generator.outputs.id }}

      - name: Push tags
        run: git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          generate_release_notes: true
          tag_name: ${{ steps.id-generator.outputs.id }}

  update-prs:
    needs: tag-release
    name: Update PRs with Labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0

      - name: Install
        uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # 3.1.1

      - name: Execute
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_USERNAME: Automattic
          PROJECT_REPONAME: vip-go-mu-plugins
          BRANCH: ${{ github.ref_name }}
        run: |
          php ./ci/update-prs.php --debug

  changelog:
    needs: update-prs
    name: Docs Site Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Extract version from PR title
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract version (YYYYMMDD.x) and check for null.
          version=$(gh api "/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" --jq '.[0].title | if . then capture(": (?<v>v[0-9]{8}\\.[0-9]+)") | .v else empty end')
          echo "version=${version:-release}" >> "$GITHUB_OUTPUT"

      - name: Create changelog
        uses: Automattic/vip-actions/changelog@2bcb000c7bae0a75493afed7cf47f4529cdd2c8e
        with:
          endpoint: 'https://docs.wpvip.com/wp-json/wp/v2/changelogs'
          endpoint-token: ${{ secrets.CHANGELOG_DOCS_POST_TOKEN }}
          endpoint-auth-type: 'basic'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          status: 'publish'
          terms: changelog_category:108
          tag-id: '112'
          link-to-pr: false
          changelog-title: "VIP MU plugins ${{ steps.version.outputs.version }}"

