name: Release - Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  update-prs:
    name: Update PRs with Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1

      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0

      - name: Install
        uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # 3.1.1

      - name: Execute
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_USERNAME: Automattic
          PROJECT_REPONAME: vip-go-mu-plugins
          BRANCH: ${{ github.ref_name }}
        run: |
          php ./ci/update-prs.php --debug

  changelog:
    needs: update-prs
    name: Docs Site Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: Automattic/vip-actions/changelog@7bc89ca324a7902844f934b4a94da222e96607bd
        with:
          endpoint: 'https://docs.wpvip.com/wp-json/wp/v2/changelogs'
          endpoint-token: ${{ secrets.CHANGELOG_DOCS_POST_TOKEN }}
          endpoint-auth-type: 'basic'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          status: 'publish'
          terms: changelog_category:109
          tag-id: '116'
          link-to-pr: false

