name: Tag Release

on:
  push:
    branches:
      - production

permissions:
  contents: read

jobs:
  tag-release:
    name: Tag Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.id-generator.outputs.id }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Check out source code
        uses: actions/checkout@v3.5.1

      - name: Retrieve tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Get tag name
        id: id-generator
        run: |
          current_date=$(date '+v%Y%m%d.')
          minor_version=0
          tag=$(git tag -l "${current_date}*" --sort=-version:refname | head -n 1)
          if [ -n "${tag}" ]; then
              minor_version=$(echo "${tag}" | awk -F. '{print $2+1}')
          fi

          echo "id=${current_date}${minor_version}" >> $GITHUB_OUTPUT

      - name: Tag release
        run: git tag ${{ steps.id-generator.outputs.id }}

      - name: Push tags
        run: git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v0.1.15
        with:
          generate_release_notes: true
          tag_name: ${{ steps.id-generator.outputs.id }}
