name: Tag Release

on:
  push:
    branches:
      - production

permissions:
  contents: read

jobs:
  tag-release:
    name: Tag Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.id-generator.outputs.id }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # tag=v1.5.0
        with:
          egress-policy: audit

      - name: Check out source code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Retrieve tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Get tag name
        id: id-generator
        run: |
          current_date=$(date '+v%Y%m%d.')
          minor_version=0
          tag=$(git tag -l "${current_date}*" --sort=-version:refname | head -n 1)
          if [ -n "${tag}" ]; then
              minor_version=$(echo "${tag}" | awk -F. '{print $2+1}')
          fi

          echo "id=${current_date}${minor_version}" >> $GITHUB_OUTPUT

      - name: Tag release
        run: git tag ${{ steps.id-generator.outputs.id }}

      - name: Push tags
        run: git push --tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # renovate: tag=v0.1.14
        with:
          generate_release_notes: true
          tag_name: ${{ steps.id-generator.outputs.id }}
