name: Verify Lock Files

on:
  pull_request:
    paths:
      - 'package-lock.json'
      - 'composer.lock'

jobs:
  verify-locks:
    permissions:
      contents: read
      pull-requests: write
    name: Verify Lock Files
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Get changed files
        run: |
          base="${{ github.event.pull_request.base.sha }}"
          head="${{ github.event.pull_request.head.sha }}"
          changes="$(git diff --merge-base --name-only "${base}" "${head}")"
          composer="$(echo "${changes}" | grep -F composer.lock)" || true
          npm="$(echo "${changes}" | grep -F package-lock.json)" || true
          echo "COMPOSER_LOCK=${composer}" >> "${GITHUB_ENV}"
          echo "PACKAGE_LOCK=${npm}" >> "${GITHUB_ENV}"

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 'lts/*'

      - name: Verify Composer changes
        id: composer_lock
        if: env.COMPOSER_LOCK
        run: |
          node .github/analyze-lockfiles.mjs ${{ env.COMPOSER_LOCK }}
          diff=$(git diff --minimal)
          if [ -n "${diff}" ]; then
            echo "changes=yes" >> "${GITHUB_OUTPUT}"
            {
              echo '## Composer Lockfile Changes'
              echo
              echo '```diff'
              echo "${diff}"
              echo '```'
              echo
              echo '**Legend:**'
              echo '  * `-`: take a closer look at this line!'
              echo '  * `+`: the replacement when the lock file gets regenerated'
              echo
              echo '**:warning: Please review these changes carefully!**'
            } > /tmp/pr-body.md
          fi

      - name: Find Comment
        if: steps.composer_lock.outputs.changes
        uses: peter-evans/find-comment@v3.0.0
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Please review these changes carefully

      - name: Post comment
        if: steps.composer_lock.outputs.changes
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: /tmp/pr-body.md
          edit-mode: replace

      - name: Disable automerge
        if: steps.composer_lock.outputs.changes
        run: |
          gh pr merge "${{ github.event.pull_request.number }}" --disable-auto || true
          gh pr review "${{ github.event.pull_request.number }}" --request-changes --body "Please manually review changes to lock files" || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
